config/routes.rb
      # require 'sidekiq-ent/web'

DbamApp::Application.routes.draw do
  mount UserImpersonate::Engine => "/impersonate", as: "impersonate_engine"
        # mount Sidekiq::Web => '/admin/sidekiq'

  root to: "dashboard#index"

  devise_for :users, controllers: { invitations: 'devise/invitations', sessions: 'users/sessions' }

  get 'workers/update_ad_source' => 'workers#update_ad_source', as: :update_ad_source

  get 'real_time', to: Metal::RealTimeController.action(:index)

  resources :placements, only: [:index] do
    member do
      post 'set_pp_name'
      get 'revenue_estimator'
    end
  end

  resources :reports, only: [] do
    collection do
      get 'placements_by_day'
      get 'account_by_day'
    end
  end

  resource :dashboard, controller: 'customer_dashboard' do
    collection do
      get 'index'
      get 'placements_by_day'
      get 'placements_by_rtb'
      get 'generate_placements_by_day_report'
      get 'account_by_day'
      get 'placements'
      get 'tags', to: 'customer_dashboard#placements'
    end
  end

  resource :demand_dashboard, controller: 'demand_dashboard' do
    collection do
      get 'index'
      get 'rtb_performance'
    end
  end

  # , path: '', constraints: { subdomain: "api" } # for forcing sub-domain and not having a second 'api' in the URL
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: :create

      resources :customers, only: [] do
        resources :tags, only: [:index] do
          member do
            get 'performance', to: 'performance#show'
          end
        end
      end
    end
    get '*unmatched_route', to: 'api#unmatched_route'
  end

  namespace :admin do
    resources :ad_source_comments
    resources :network_comments
    resources :placement_comments
    resources :customer_comments
    resources :ad_source_groups
    resources :fpf do
      get 'calculate_on_demand', on: :member
    end
    resources :queries do
      get :new_for_home_page, on: :collection
    end
    resources :rtb_network_pies do
      get :populate_table, on: :collection
    end

    resources :network_users, except: [:index] do
      get :network_list, on: :collection
      get :confirm, on: :member
      get :sign_in_info, on: :member
      get :invitation_info, on: :member
      get :versions, on: :collection
    end
    resources :customer_users, except: [:index] do
      get :customer_list, on: :collection
      get :confirm, on: :member
      get :sign_in_info, on: :member
      get :invitation_info, on: :member
      get :versions, on: :collection
    end
    resources :dashbid_users, except: [:index] do
      get :dashbid_list, on: :collection
      get :confirm, on: :member
      get :sign_in_info, on: :member
      get :invitation_info, on: :member
      get :versions, on: :collection
    end

    resources :home, only: [:index] do
      collection do
        get 'check_ad_source_no_fill'
        get 'clear_cookie'
        get 'customer_status'
        post 'customer_status'
        get 'explore_data'
        get 'network_status'
        get 'reports'
        get 'server_status'
        get 'whats_new'
        get 'deploys'
        get 'customers_from_account_contact'
        get 'real_time_test'
      end
    end

    # why 2x? [once above, once here]
    get 'clear_cookie'  => 'home#clear_cookie'
    get 'dbams/configs' => "dbams#configs" # Ugh awful for AJAX

    get 'td'                => 'td#index'
    get 'td/:table/schema'  => 'td#schema'
    get 'td/:table/tail/:n' => 'td#tail'

    get 'ad_source_hourly/base', to: 'ad_source_hourly#base'
    get 'ad_source_hourly/pivot', to: 'ad_source_hourly#pivot'

    get 'ad_source_hourly', to: 'ad_source_hourly#index'

    get 'placement_dashboard', to: 'placement_dashboard#index'

    get 'real_time', to: 'real_time#index'

    get 'td_api/templates',    to: 'td_api#templates'
    get 'td_api/download_csv', to: 'td_api#download_csv'
    post 'td_api/run',         to: 'td_api#run'
    post 'td_api/kill_job',    to: 'td_api#kill_job'

    resources :activity_logs, only: [:index] do
      collection do
        get 'activities'
        get 'activity_users'
        get 'activity_user_detail'
        get 'activity_detail'
      end
    end

    resources :ad_source_reconciliations do
      member do
        post "edit_int"
      end
    end

    resources :ad_sources do
      member do
        get 'copy'
        get 'network_data'
        get 'versions'
        get 'comments'
        get 'waterfalls'
        get 'bag_of_tags'
        post 'save_groups'
        get 'ad_source_groups'
      end
      collection do
        get 'ad_source_map2'
        get 'list'
        get 'list_assignments'
        get 'player_sizes'
      end
      resources :ad_source_reconciliations, only: ["index"]
    end

    resources :build_tests, only: [:show, :edit, :update, :destroy, :run, :run_parent] do
      member do
        get '_dbam'
        get 'dbam_script'
        get 'pass'
        get 'run'
        get 'run_parent'
        get 'unpass'
      end
    end

    resources :build_tests

    resources :countries do
      member do
        post :activate
        post :deactivate
      end
      collection do
        get 'list'
      end
    end

    resources :customers, constraints: { id: /[0-9]+/ } do
      collection do
        get 'hourly_check'
      end

      member do
        get 'checkout'
        get 'commits'
        get 'deploys'
        get 'history'
        get 'placements'
        get 'pull'
        get 'repo'
        get 'reset'
        get 'users'
        get 'versions'
        get 'comments'
      end

      resources :daily_revenues

      resources 'generate_text', controller: 'customer_generate_text', only: [:index] do
        collection do
          get 'export'
        end
      end

      resources 'margins', controller: 'customer_margins', only: [:index]
      resources 'placement_margins', controller: 'customer_placement_margins', only: [:show]

      ## TODO jb: use shallow in rails 4!
      resources :placements, except: [:show, :edit, :update, :destroy] do
      end

      resources 'td_ad_sources', controller: 'customer_td_ad_sources', only: [:index]
    end

    resources :customer_statements, only: [:index] do
      collection do
        get '/', to: 'customer_statements#all_months'
        get 'all_months'
        get 'month_by_day'
        get 'month_by_customer'
        get 'day_by_customer'
        get 'customer_month_by_day'
        get 'customer_day_by_placement'
      end
    end

    resources :customer_statement_dates, only: [:index] do
      collection do
        get 'all_months'
        get 'month_by_day'
        get 'billing_template'
        get 'generate_date'
        post 'generate_all_dates_by_month'
        get 'lock_date'
        get 'unlock_date'
        get 'unlock_dbif_date'
        get 'lock_dbif_date'
        get 'lock_all_dates'
        get 'lock_all_fpf_dates'
      end
    end

    resources :data_explorers do
      collection do
        get 'ad_source_hourly', to: redirect('/admin/ad_source_hourly')
        get 'ad_source_daily'
        get 'domain_hourly'
        get 'network'
        get 'network3'
        get 'network_pivot'
        get 'network_heat_map'
        get 'placements'
        get 'ad_sources'
        get 'server_performance_hourly'
        get 'waterfall_daily'
        get 'waterfall_hourly'
        get 'waterfall_hourly_to_csv'
      end
    end

    resources :data_sources

    resources :dbam_builds, only: [:show, :destroy]   do
      member do
        get 'build_waterfall'
        get 'dbam_commit'
        get 'git_file'
        get 'target_commit'
      end
      resources :build_tests, except: [:show, :edit, :update, :destroy]
      resources :deploys, except: [:show, :edit, :update, :destroy]
    end

    resources :dbams do
      member do
        get 'checkout'
        get 'placements'
        get 'pull'
        get 'reset'
      end
    end

    resources :definitions do
      collection do
        get 'list'
      end
    end

    resources :deploys, only: [:index, :show, :new, :create]

    resources :domains, only: [:index, :show] do
      collection do
        get 'list'
      end
    end

    get 'help', to: 'resources#index'

    resources :resources, only: [:index] do
      collection do
      end
    end


    resources :groups do
      collection do
        get 'add_placement'
      end
      member do
        get 'add_ad_source'
        get 'remove_placement'
        get 'edit_ad_source_group'
        get 'remove_ad_source'
      end
    end

    resources :health_check, only: [:index] do
      collection do
        get 'td_wf_events_job'
        get 'td_as_events_job'
      end
    end

    resources :hourly_margin_dates, only: [:index] do
      collection do
        get 'all_months'
        get 'month_by_day'
        get 'generate_day_data'
        get 'generate_month_data'
        post 'generate_selected_days_data'
        post 'generate_outdated_days_data'
      end
    end

    resources :infrastructure_fees, only: [:index] do
      collection do
        get 'all_months'
        get 'month_by_day'
        get 'generate_date'
        post 'generate_all_dates_by_month'
      end
    end

    resources :jobs, only: [:index] do
      collection do
        get 'purge_td_domain_referrers'
        post 'purge_td_domain_referrers_do'
        get 'purge_td_domain_http_referers'
        post 'purge_td_domain_http_referers_do'
        get 'derive_margin_data'
        post 'derive_margin_data_do'
        get 'mysql_processes'
        get 'kill_mysql_process'
        get 'explain_mysql_process'
        get :not_used_lists
        post :delete_not_used_lists
        get :delete_all_not_used_lists
        get :delete_checked_unused_lists
        get :import_pixalate_ip_list
        post :import_pixalate_ip_list_post
      end
    end

    resources :list_assignment_groups, except: [:destroy] do

app/controllers/admin/customer_statement_dates_controller.rb
class Admin::CustomerStatementDatesController < AdminController
  include AdminHelper
  include GetRecordByIdHelper

  before_action :authorize!, only: [:index]

  def index
    # RBT: TODO: Refactor this!
    month_by_day
    render 'month_by_day'
  end

  def all_months
    @months = CustomerStatementDate.by_month
  end

  def month_by_day
    if @year_month = params[:year_month] || Time.zone.now.strftime('%Y-%m')
      params_hash = { year_month: @year_month }
      CustomerStatementDate.add_missing_days(params_hash)
      @month_by_day = CustomerStatementDate.month_by_day(params_hash)
      this_month = ("#{@year_month}-01").to_date
      @prev_month = (this_month - 1.month).strftime('%Y-%m')
      @next_month = (this_month + 1.month).strftime('%Y-%m')
    else
      @month_by_day = []
    end
  end

  def lock_date
    if record = CustomerStatementDate.where(:dd => params[:dd]).first
      if record.locked_dt
        flash[:notice] = "'#{record.dd}' is ALREADY LOCKED"
      else
        attr_hash = {
            locked_dt: Time.now.to_datetime,
            locked_by_id: current_user.id,
            dbif_locked_at: record.dbif_locked_at || Time.now.to_datetime
        }
        #
        if record.update_attributes(attr_hash)
          flash[:notice] = "'#{record.dd}' is now LOCKED"
        else
          flash[:alert] = "'#{record.dd}' locking FAILED"
        end
      end
    else
      flash[:alert] = 'Record not found!'
    end

    redirect_to month_by_day_admin_customer_statement_dates_path({ year_month: params[:year_month] })
  end

  def lock_all_dates
      start_date = ("#{params[:year_month]}-01").to_date
      end_date = [start_date.end_of_month, Time.now.to_date - 1.day].min

      (start_date..end_date).each do |date|
        cs = CustomerStatementDate.find_by_dd(date)
        cs.locked_dt = cs.locked_dt.nil? ? Time.now.to_datetime : nil
        cs.locked_by_id = cs.locked_by_id.nil? ? current_user.id : nil
        cs.save
      end

    redirect_to month_by_day_admin_customer_statement_dates_path({:year_month => params[:year_month]})  
  end

  def lock_all_fpf_dates
      start_date = ("#{params[:year_month]}-01").to_date
      end_date = [start_date.end_of_month, Time.now.to_date - 1.day].min

      (start_date..end_date).each do |date|
        cs = CustomerStatementDate.find_by_dd(date)
        cs.dbif_locked_at = cs.dbif_locked_at.nil? ? Time.now.to_datetime : nil
        cs.save
      end

    redirect_to month_by_day_admin_customer_statement_dates_path({:year_month => params[:year_month]})      
  end

  def lock_dbif_date
    if record = CustomerStatementDate.where(:dd => params[:dd]).first
       record.update(dbif_locked_at: Time.now.to_datetime)
    else
       flash[:alert] = 'Record not found!'
    end

    redirect_to month_by_day_admin_customer_statement_dates_path({:year_month => params[:year_month]})    
  end

  def unlock_dbif_date
    if record = CustomerStatementDate.where(:dd => params[:dd]).first
       record.update(dbif_locked_at: nil)
    else
       flash[:alert] = 'Record not found!'
    end

    redirect_to month_by_day_admin_customer_statement_dates_path({:year_month => params[:year_month]})    
  end


  def authorize!
    authorize CustomerStatementDate, :allow?
  end
  
  def unlock_date
    if record = CustomerStatementDate.where(:dd => params[:dd]).first
      unless record.locked_dt
        flash[:notice] = "'#{record.dd}' is ALREADY UNLOCKED"
      else
        attr_hash = {
            :locked_dt => nil,
            :locked_by_id => nil
        }
        if record.update_attributes(attr_hash)
          flash[:notice] = "'#{record.dd}' is now UNLOCKED"
        else
          flash[:alert] = "'#{record.dd}' unlocking FAILED"
        end
      end
    else
      flash[:alert] = 'Record not found!'
    end

    redirect_to month_by_day_admin_customer_statement_dates_path({:year_month => params[:year_month]})
  end

  def generate_date
    if params[:dd].present?
      run_date = params[:dd]
      CustomerStatementDatesGenerateWorker.perform_async(run_date, run_date)
      flash[:notice] = "A background job have been submitted for to process Customer Statement for all customers on #{run_date}."
    else
      flash[:error] = 'Date param not found. It is needed to schedule Customer Statements job. Please try again with a date param (dd).'
    end

    redirect_to month_by_day_admin_customer_statement_dates_path(year_month: params[:year_month])
  end

  def generate_all_dates_by_month
    if params[:year_month].present?
      CustomerStatementDatesGenerateByMonthWorker.perform_async(params[:year_month])
      flash[:notice] = "A background job have been submitted for to process all possible Customer Statements for all customers in this month."
      redirect_to month_by_day_admin_customer_statement_dates_path(year_month: params[:year_month])
    else
      flash[:error] = 'Date param not found. It is needed to schedule Customer Statements job. Please try again using the "Calclate all dates for this Month" button.'
      redirect_to all_months_admin_customer_statement_dates_path
    end
  end

  def billing_template
    if params[:year_month]
      selected_month = params[:year_month]
      selected_month_date = ("#{selected_month}-01").to_date

      year_month = selected_month_date.strftime('%Y-%m')
      file_name = "billing_template_#{year_month}"

      start_date = selected_month_date.beginning_of_month
      end_date = selected_month_date.end_of_month

      @networks_data = NetworkDatum.by_network(start_date, end_date)
      @publishers_data = CustomerStatement.month_by_customer({:year_month => year_month})
      render xlsx: "billing_template", filename: file_name
    else
      flash[:alert] = 'Billing Template generation failed'
      redirect_to month_by_day_admin_customer_statement_dates_path({:year_month => params[:year_month]})

    end
  end
end

app/views/admin/customer_statement_dates/all_months.html.erb
<h1>Generate Customer Statement Data / Billing Template</h1>

<table class="table-with-borders">
  <tr>
    <th>Year-Month</th>
  </tr>

  <% @months.each do |row| %>
    <tr>
      <td class="td-center bold">
        <%= link_to row.year_and_month,
                    {:action => 'month_by_day', :year_month => row.year_and_month},
                    :title => 'by Day' %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/customer_statement_dates/month_by_day.html.erb
<%# datetime_format = '%m-%d %l:%M%P' %>
<% datetime_format = '%m-%d %H:%M' %>

<%= link_to 'All Months', {:action => 'all_months'}, :class => 'subnav-link' %>

<h1>Generate Customer Statement Data / Billing Template</h1>

<p>
  <%= link_to "#{fa_icon2(['angle-left', :lg])} Previous month".html_safe, month_by_day_admin_customer_statement_dates_path(year_month: @prev_month), title: 'Previous Month', class: 'btn btn-default btn-sm' %>

  <span class="bold">Current month: <%= @year_month %></span>

  <%= link_to "Next month #{fa_icon2(['angle-right', :lg])}".html_safe, month_by_day_admin_customer_statement_dates_path(year_month: @next_month), title: 'Next Month', class: 'btn btn-default btn-sm' %>
</p>

<p>
  <%= link_to 'Generate Billing Template', billing_template_admin_customer_statement_dates_path(year_month: @year_month), class: 'btn btn-default btn-sm' %>

  <%= link_to "Calculate all dates for this month", generate_all_dates_by_month_admin_customer_statement_dates_path(year_month: @year_month), method: :post, class: 'btn btn-primary btn-sm' if @month_by_day.select{|date| date.earliest_dt.present? && date.latest_reconcile_dt.present? && date.earliest_dt >= date.latest_reconcile_dt }.any? %>
</p>

<table class="table-with-borders">
  <tr>
    <th>Day</th>
    <th><%= fa_icon2([:lock,:lg]) %></th>
    <th><%= link_to "<i class='fa fa-lock' aria-hidden='true'></i>&nbsp;#{get_link_text(@month_by_day,:not_locked)}".html_safe, 
            lock_all_dates_admin_customer_statement_dates_path(year_month: @year_month), class: 'subnav-link', 
            data: { confirm: "Are you sure?" } %></th>
    <th>Calculated<br>Date/Time</th>
    <th>Reconciled<br>Impressions</th>
    <th>Customer<br>Payout</th>
    <th class="nowrap">&gt;<br>or &lt;</th>
    <th>Most Recent<br>Reconciliation</th>
    <th>Locked At</th>
    <th></th>
    <th>Waterfall<br>Requests</th>
    <th>Waterfall<br>Impressions</th>
    <th title="Fraud Protection Fees">FP Fees</th>
    <th>Lock<br>FP Rates<br>
        <%= link_to "<i class='fa fa-lock' aria-hidden='true'></i>&nbsp;#{get_link_text(@month_by_day,:dbif_not_locked)}".html_safe, 
            lock_all_fpf_dates_admin_customer_statement_dates_path(year_month: @year_month), class: 'subnav-link', 
            data: { confirm: "Are you sure?" } %></th>
  </tr>

  <% @month_by_day.each do |row| %>
    <tr>
      <td class="td-center nowrap bold"  <% if row.locked_dt? %>style="background-color: #CBFDCB"<% end %>>
        <%= row.dd.strftime('%m-%d') %>
      </td>

      <td  <% if row.locked_dt? %>style="background-color: #CBFDCB"<% end %>>
        <% if row.locked_dt? %>
          <%= fa_icon2([:lock,:lg],'text-danger') %>
        <% end %>
      </td>

      <td class="td-center nowrap"  <% if row.locked_dt? %>style="background-color: #CBFDCB"<% end %>>
        <% if_admin do %>
          <% if row.locked_dt? %>
            <%= link_to 'Unlock Day',
                        {:action => 'unlock_date', :year_month => @year_month, :dd => row.dd},
                        :class => 'btn btn-xs btn-default' %>
          <% else %>
            <%= link_to 'Calculate',
                        {:action => 'generate_date', :year_month => @year_month, :dd => row.dd},
                        :class => 'btn btn-xs btn-default' %>
            <%= link_to 'Lock Day',
                        {:action => 'lock_date', :year_month => @year_month, :dd => row.dd},
                        :class => 'btn btn-xs btn-default' %>
          <% end %>
        <% end %>
      </td>

      <td class="td-center nowrap"  <% if row.locked_dt? %>style="background-color: #CBFDCB"<% end %>>
        <%= row.earliest_dt.in_time_zone.strftime(datetime_format) if row.earliest_dt %>
      </td>

      <td class="td-right" <% if row.locked_dt? %>style="background-color: #CBFDCB"<% end %>>
        <%= number_with_delimiter(row.impressions, :delimiter => ',') %>
      </td>
      <td class="td-right" <% if row.locked_dt? %>style="background-color: #CBFDCB"<% end %>>
        <%= number_to_currency( row.revenue, :precision => 2 ) %>
      </td>

      <% if row.earliest_dt && row.latest_reconcile_dt %>
        <% if row.earliest_dt < row.latest_reconcile_dt %>
          <% x_compared = '<' %>
          <% x_style = "background-color: #FF9999;" %>
        <% else %>
          <% x_compared = '>' %>
          <% x_style = "" %>
        <% end %>
      <% end %>
      <% if row.locked_dt? and x_style.blank? %>
        <% x_style="background-color: #CBFDCB"%>
      <% end %>
      <td class="td-center" style="<%= x_style %>">
        <%= x_compared %>
      </td>

      <td class="td-center nowrap" <% if row.locked_dt? %>style="background-color: #CBFDCB"<% end %>>
        <%= row.latest_reconcile_dt.in_time_zone.strftime(datetime_format) if row.latest_reconcile_dt %>
      </td>

      <td class="td-center nowrap" title="<%= "locked by #{row.locked_by_email}" if row.locked_by_email %>"  <% if row.locked_dt? %>style="background-color: #CBFDCB"<% end %>>
        <%= row.locked_dt.strftime(datetime_format) if row.locked_dt %>
      </td>

      <td></td>
      <td class="td-right" <% if row.locked_dt? || row.dbif_locked_at? %>style="background-color: #CBFDCB"<% end %>>
        <%= number_with_delimiter(row.wf_requests_sum, :delimiter => ',') %>
      </td>
      <td class="td-right" <% if row.locked_dt? || row.dbif_locked_at? %>style="background-color: #CBFDCB"<% end %>>
        <%= number_with_delimiter(row.wf_impressions_sum, :delimiter => ',') %>
      </td>
      <td class="td-right" <% if row.locked_dt? || row.dbif_locked_at? %>style="background-color: #CBFDCB"<% end %>>
        <%= number_to_currency( row.dbif_fee_sum, :precision => 2 ) %>
      </td>
      <td class="td-center nowrap" <% if row.locked_dt? || row.dbif_locked_at? %>style="background-color: #CBFDCB"<% end %>>
        <% unless row.locked_dt  %>
          <% if row.dbif_locked_at %>
            <%= link_to 'Unlock FP Rates',
                        {:action => 'unlock_dbif_date', :year_month => @year_month, :dd => row.dd},
                        :class => 'btn btn-xs btn-default' %>
          <% else %>
              <%= link_to 'Lock FP Rates',
                          {:action => 'lock_dbif_date', :year_month => @year_month, :dd => row.dd},
                          :class => 'btn btn-xs btn-default' %>
          <% end %>
        <% end %>
      </td>

    </tr>
  <% end %>
</table>

<% content_for :footnotes do %>
  <hr>
  <ol class="numbered-list" style="padding-top: 5px;">
    Note:
    <li>FP Fee = Fraud Protection Fee, only applies to mobile placement.</li>
  </ol>
<% end %>