config/routes.rb
      # require 'sidekiq-ent/web'

DbamApp::Application.routes.draw do
  mount UserImpersonate::Engine => "/impersonate", as: "impersonate_engine"
        # mount Sidekiq::Web => '/admin/sidekiq'

  root to: "dashboard#index"

  devise_for :users, controllers: { invitations: 'devise/invitations', sessions: 'users/sessions' }

  get 'workers/update_ad_source' => 'workers#update_ad_source', as: :update_ad_source

  get 'real_time', to: Metal::RealTimeController.action(:index)

  resources :placements, only: [:index] do
    member do
      post 'set_pp_name'
      get 'revenue_estimator'
    end
  end

  resources :reports, only: [] do
    collection do
      get 'placements_by_day'
      get 'account_by_day'
    end
  end

  resource :dashboard, controller: 'customer_dashboard' do
    collection do
      get 'index'
      get 'placements_by_day'
      get 'placements_by_rtb'
      get 'generate_placements_by_day_report'
      get 'account_by_day'
      get 'placements'
      get 'tags', to: 'customer_dashboard#placements'
    end
  end

  resource :demand_dashboard, controller: 'demand_dashboard' do
    collection do
      get 'index'
      get 'rtb_performance'
    end
  end

  # , path: '', constraints: { subdomain: "api" } # for forcing sub-domain and not having a second 'api' in the URL
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: :create

      resources :customers, only: [] do
        resources :tags, only: [:index] do
          member do
            get 'performance', to: 'performance#show'
          end
        end
      end
    end
    get '*unmatched_route', to: 'api#unmatched_route'
  end

  namespace :admin do
    resources :ad_source_comments
    resources :network_comments
    resources :placement_comments
    resources :customer_comments
    resources :ad_source_groups
    resources :fpf do
      get 'calculate_on_demand', on: :member
    end
    resources :queries do
      get :new_for_home_page, on: :collection
    end
    resources :rtb_network_pies do
      get :populate_table, on: :collection
    end

    resources :network_users, except: [:index] do
      get :network_list, on: :collection
      get :confirm, on: :member
      get :sign_in_info, on: :member
      get :invitation_info, on: :member
      get :versions, on: :collection
    end
    resources :customer_users, except: [:index] do
      get :customer_list, on: :collection
      get :confirm, on: :member
      get :sign_in_info, on: :member
      get :invitation_info, on: :member
      get :versions, on: :collection
    end
    resources :dashbid_users, except: [:index] do
      get :dashbid_list, on: :collection
      get :confirm, on: :member
      get :sign_in_info, on: :member
      get :invitation_info, on: :member
      get :versions, on: :collection
    end

    resources :home, only: [:index] do
      collection do
        get 'check_ad_source_no_fill'
        get 'clear_cookie'
        get 'customer_status'
        post 'customer_status'
        get 'explore_data'
        get 'network_status'
        get 'reports'
        get 'server_status'
        get 'whats_new'
        get 'deploys'
        get 'customers_from_account_contact'
        get 'real_time_test'
      end
    end

    # why 2x? [once above, once here]
    get 'clear_cookie'  => 'home#clear_cookie'
    get 'dbams/configs' => "dbams#configs" # Ugh awful for AJAX

    get 'td'                => 'td#index'
    get 'td/:table/schema'  => 'td#schema'
    get 'td/:table/tail/:n' => 'td#tail'

    get 'ad_source_hourly/base', to: 'ad_source_hourly#base'
    get 'ad_source_hourly/pivot', to: 'ad_source_hourly#pivot'

    get 'ad_source_hourly', to: 'ad_source_hourly#index'

    get 'placement_dashboard', to: 'placement_dashboard#index'

    get 'real_time', to: 'real_time#index'

    get 'td_api/templates',    to: 'td_api#templates'
    get 'td_api/download_csv', to: 'td_api#download_csv'
    post 'td_api/run',         to: 'td_api#run'
    post 'td_api/kill_job',    to: 'td_api#kill_job'

    resources :activity_logs, only: [:index] do
      collection do
        get 'activities'
        get 'activity_users'
        get 'activity_user_detail'
        get 'activity_detail'
      end
    end

    resources :ad_source_reconciliations do
      member do
        post "edit_int"
      end
    end

    resources :ad_sources do
      member do
        get 'copy'
        get 'network_data'
        get 'versions'
        get 'comments'
        get 'waterfalls'
        get 'bag_of_tags'
        post 'save_groups'
        get 'ad_source_groups'
      end
      collection do
        get 'ad_source_map2'
        get 'list'
        get 'list_assignments'
        get 'player_sizes'
      end
      resources :ad_source_reconciliations, only: ["index"]
    end

    resources :build_tests, only: [:show, :edit, :update, :destroy, :run, :run_parent] do
      member do
        get '_dbam'
        get 'dbam_script'
        get 'pass'
        get 'run'
        get 'run_parent'
        get 'unpass'
      end
    end

    resources :build_tests

    resources :countries do
      member do
        post :activate
        post :deactivate
      end
      collection do
        get 'list'
      end
    end

    resources :customers, constraints: { id: /[0-9]+/ } do
      collection do
        get 'hourly_check'
      end

      member do
        get 'checkout'
        get 'commits'
        get 'deploys'
        get 'history'
        get 'placements'
        get 'pull'
        get 'repo'
        get 'reset'
        get 'users'
        get 'versions'
        get 'comments'
      end

      resources :daily_revenues

      resources 'generate_text', controller: 'customer_generate_text', only: [:index] do
        collection do
          get 'export'
        end
      end

      resources 'margins', controller: 'customer_margins', only: [:index]
      resources 'placement_margins', controller: 'customer_placement_margins', only: [:show]

      ## TODO jb: use shallow in rails 4!
      resources :placements, except: [:show, :edit, :update, :destroy] do
      end

      resources 'td_ad_sources', controller: 'customer_td_ad_sources', only: [:index]
    end

    resources :customer_statements, only: [:index] do
      collection do
        get '/', to: 'customer_statements#all_months'
        get 'all_months'
        get 'month_by_day'
        get 'month_by_customer'
        get 'day_by_customer'
        get 'customer_month_by_day'
        get 'customer_day_by_placement'
      end
    end

    resources :customer_statement_dates, only: [:index] do
      collection do
        get 'all_months'
        get 'month_by_day'
        get 'billing_template'
        get 'generate_date'
        post 'generate_all_dates_by_month'
        get 'lock_date'
        get 'unlock_date'
        get 'unlock_dbif_date'
        get 'lock_dbif_date'
        get 'lock_all_dates'
        get 'lock_all_fpf_dates'
      end
    end

    resources :data_explorers do
      collection do
        get 'ad_source_hourly', to: redirect('/admin/ad_source_hourly')
        get 'ad_source_daily'
        get 'domain_hourly'
        get 'network'
        get 'network3'
        get 'network_pivot'
        get 'network_heat_map'
        get 'placements'
        get 'ad_sources'
        get 'server_performance_hourly'
        get 'waterfall_daily'
        get 'waterfall_hourly'
        get 'waterfall_hourly_to_csv'
      end
    end

    resources :data_sources

    resources :dbam_builds, only: [:show, :destroy]   do
      member do
        get 'build_waterfall'
        get 'dbam_commit'
        get 'git_file'
        get 'target_commit'
      end
      resources :build_tests, except: [:show, :edit, :update, :destroy]
      resources :deploys, except: [:show, :edit, :update, :destroy]
    end

    resources :dbams do
      member do
        get 'checkout'
        get 'placements'
        get 'pull'
        get 'reset'
      end
    end

    resources :definitions do
      collection do
        get 'list'
      end
    end

    resources :deploys, only: [:index, :show, :new, :create]

    resources :domains, only: [:index, :show] do
      collection do
        get 'list'
      end
    end

    get 'help', to: 'resources#index'

    resources :resources, only: [:index] do
      collection do
      end
    end


    resources :groups do
      collection do
        get 'add_placement'
      end
      member do
        get 'add_ad_source'
        get 'remove_placement'
        get 'edit_ad_source_group'
        get 'remove_ad_source'
      end
    end

    resources :health_check, only: [:index] do
      collection do
        get 'td_wf_events_job'
        get 'td_as_events_job'
      end
    end

    resources :hourly_margin_dates, only: [:index] do
      collection do
        get 'all_months'
        get 'month_by_day'
        get 'generate_day_data'
        get 'generate_month_data'
        post 'generate_selected_days_data'
        post 'generate_outdated_days_data'
      end
    end

    resources :infrastructure_fees, only: [:index] do
      collection do
        get 'all_months'
        get 'month_by_day'
        get 'generate_date'
        post 'generate_all_dates_by_month'
      end
    end

    resources :jobs, only: [:index] do
      collection do
        get 'purge_td_domain_referrers'
        post 'purge_td_domain_referrers_do'
        get 'purge_td_domain_http_referers'
        post 'purge_td_domain_http_referers_do'
        get 'derive_margin_data'
        post 'derive_margin_data_do'
        get 'mysql_processes'
        get 'kill_mysql_process'
        get 'explain_mysql_process'
        get :not_used_lists
        post :delete_not_used_lists
        get :delete_all_not_used_lists
        get :delete_checked_unused_lists
        get :import_pixalate_ip_list
        post :import_pixalate_ip_list_post
      end
    end

    resources :list_assignment_groups, except: [:destroy] do

app/views/layouts/_admin_nav.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">

  <div id="env-info" class="hidden">
    <% host = AppInfo.host.sub('.amazonaws.com', '') %>
    <div class="nowrap">
      <span class="admin-nav-label" style="background-color:#ff8080;">Admin</span>
      <span class="admin-nav-label">HOST: <%= host %></span>
      <% unless AppInfo.stage.production? %>
        <span class="admin-nav-label">STAGE: <%= AppInfo.stage if !AppInfo.stage.production? %></span>
      <% end %>
      <span class="admin-nav-label" title="<%= "#{AppInfo.commit}" %>"><%="COMMIT: #{AppInfo.commit[0,7]}..." %></span>
      <span class="admin-nav-label">DB TIME: <%= in_EST(Time.now,"%Y-%m-%d %H:%M %Z") %></span>
    </div>
    <div class="clear"></div>
  </div>

  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'DashBid Ad Manager', root_path, id: 'main-logo', class: 'navbar-brand' %>
    </div>

    <div class="navbar-collapse collapse nowrap">
      <ul class="nav navbar-nav">

        <li class="dropdown <%= active_menu2(['customers', 'customer_status', 'customer_generate_text', 'customer_margins']) %>">
          <%= link_to raw('Customers' +("<b class= 'caret'></b>")), admin_customers_path, class: "dropdown-toggle active_menu2('customers')" %>
          <ul class="dropdown-menu">
            <li class="<%= active_menu2('customers', 'index') %>"><%= link_to 'Customers', admin_customers_path %></li>
            <li class="<%= active_menu2('customers', 'new') %>"><%= link_to 'New Customer', new_admin_customer_path %></li>
            <li class="<%= active_menu2('home', 'customer_status') %>">
              <%= link_to 'Customer Status', customer_status_admin_home_index_path %>
            </li>
            <li class="<%= active_menu2('customer_domain_report', 'index') %>">
              <%= link_to 'Customer Domain Spreadsheet', admin_customer_domain_report_index_path %>
            </li>
            <li class="<%= active_menu2('fpf', 'index') %>">
              <%= link_to 'Customer Fraud Protection Fees', admin_fpf_index_path %>
            </li>
            <%= recent_items_for_nav(:customers) %>
          </ul>
        </li>

        <li class="dropdown <%= active_menu2('placements') %>">
          <%= link_to raw('Placements' + ("<b class= 'caret'></b>")), admin_placements_path,
            class: "dropdown-toggle active_menu2('placements')"%>
          <ul class="dropdown-menu">
            <li class="<%= active_menu2('placements') %>"><%= link_to 'Placements', admin_placements_path %></li>
            <li class="<%= active_menu2('placement_groups') %>"><%= link_to 'Placements - Groups', admin_placement_groups_path %></li>
            <%= recent_items_for_nav(:placements) %>
          </ul>
        </li>

        <li class="dropdown <%= active_menu2(['networks', 'network_data', 'network_reconciliations', 'uploads']) %>">
          <%= link_to raw('Networks' +("<b class= 'caret'></b>")), admin_networks_path, class: "dropdown-toggle active_menu2('network')" %>
          <ul class="dropdown-menu">
            <li class="<%= active_menu2('networks') %>"><%= link_to 'Networks', admin_networks_path%></li>
            <li class="<%= active_menu2('home', 'network_status') %>">
              <%= link_to 'Network Status (dbam)', network_status_admin_home_index_path %>
            </li>

            <li class="divider"></li>

            <li class="<%= active_menu2('network_reconciliations', 'index') %>">
              <%= link_to 'Network Reconciliations', admin_network_reconciliations_path %>
            </li>
            <li class="<%= active_menu2('network_reconciliations', 'missing') %>">
              <%= link_to 'Missing Network Reconciliations', missing_admin_network_reconciliations_path %>
            </li>
            <li class="<%= active_menu2('network_data', 'index') %>"><%= link_to 'Network Data', admin_network_data_path%></li>
            <li class="<%= active_menu2('uploads') %>">
              <%= link_to 'Network Uploads', admin_uploads_path%>
            </li>
            <% if policy(Navigation).user_can?(:see_reconciliation_team_actions) %>
              <li class="<%= active_menu2('network_data', 'status') %>">
                <%= link_to 'Network Data - Upload Status', status_admin_network_data_path %>
              </li>
            <% end %>
            <% if policy(Navigation).user_can?(:see_finance_team_links) %>
              <li class="<%= active_menu2('customer_statement_dates') %>">
                <%= link_to 'Customer Statements', month_by_day_admin_customer_statement_dates_path%>
              </li>
            <% end %>
            <li class="<%= active_menu2('margin_report_hourly') %>">
              <%= link_to 'Hourly Margin Report', admin_margin_report_hourly_index_path%>
            </li>
          </ul>
        </li>

        <li class="dropdown <%= active_menu2('ad_sources') %>">
          <%= link_to raw('Ad Sources' + ("<b class= 'caret'></b>")), admin_ad_sources_path,
                      class: "dropdown-toggle active_menu2('ad_sources')" %>

          <ul class="dropdown-menu">
            <li class="<%= active_menu2('ad_sources', 'index') %>">
              <%= link_to 'Ad Sources', admin_ad_sources_path %>
            </li>

            <li class="<%= active_menu2('ad_sources', 'player_sizes') %>">
              <%= link_to 'Ad Sources - Player Sizes', player_sizes_admin_ad_sources_path %>
            </li>
            <%= recent_items_for_nav(:ad_sources) %>
          </ul>
        </li>

        <li class="dropdown <%= active_menu2('data_explorers') %>">
          <a href="#" class="dropdown-toggle <%= active_menu2('reports') %>" data-toggle="dropdown">Reports <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li class="<%= active_menu2('network_revenue_daily', 'index') %>">
              <%= link_to 'Network Revenue - Daily', admin_network_revenue_daily_index_path %>
            </li>
            <li class="<%= active_menu2('data_explorers', 'network3') %>">
              <%= link_to 'Network Revenue Graph (~Daily)', network3_admin_data_explorers_path %>
            </li>
            <li class="<%= active_menu2('pivot', 'network') %>"><%= link_to 'Network Pivot!', network_admin_pivot_index_path %></li>
            <li class="<%= active_menu2('network_revenues', 'index') %>">
              <%= link_to 'Network Revenue (~Monthly)', admin_network_revenues_path %>
            </li>

            <li class="divider"></li>
            <li class="<%= active_menu2('margin_report_index', 'index') %>">
              <%= link_to 'Margin Report', admin_margin_report_index_path %>
            </li>
            <li class="<%= active_menu2('margin_report_beta', 'index') %>">
              <%= link_to 'Margin Report - BETA', admin_margin_report_beta_path %>
            </li>

            <li class="divider"></li>
            <li class="<%= active_menu2('waterfall_reports', 'by_hour') %>">
              <%= link_to 'Waterfall by Hour / Day / Month', by_hour_admin_waterfall_reports_path %>
            </li>

            <li class="<%= active_menu2('waterfall_reports', 'by_placements') %>">
              <%= link_to 'Waterfall by Placement', by_placements_admin_waterfall_reports_path %>
            </li>

            <li class="<%= active_menu2('data_explorers', 'waterfall_hourly') %>">
              <%= link_to 'Waterfall Hourly [No CC]', waterfall_hourly_admin_data_explorers_path %>
            </li>
            <li class="<%= active_menu2('data_explorers', 'waterfall_daily') %>">
              <%= link_to 'Waterfall Daily [With CC]', waterfall_daily_admin_data_explorers_path %>
            </li>

            <li class="divider"></li>

            <li class="<%= active_menu2('ad_source_hourly', 'index') %>">
              <%= link_to 'Ad Source Hourly', admin_ad_source_hourly_path %>
            </li>

            <li class="<%= active_menu2('data_explorers', 'ad_source_daily') %>">
              <%= link_to 'Ad Source Daily [With CC]', ad_source_daily_admin_data_explorers_path %>
            </li>

            <li class="divider"></li>

            <li class="<%= active_menu2('domain_referrer', 'index') %>">
              <%= link_to 'Domain Referrer', admin_domain_referrers_path %>
            </li>

            <li class="<%= active_menu2('domain_http_referrer', 'index') %>">
              <%= link_to 'Domain Referrer (with HTTP_Referer)', admin_domain_http_referers_path %>
            </li>

            <% if policy(Navigation).user_can?(:see_td_queries_user_actions) %>
              <li class="divider"></li>
              <li class="<%= active_menu2('td_api', 'templates') %>">
                <%= link_to 'Self Service Reports', admin_td_api_templates_path %>
              </li>
            <% end %>

            <% if policy(Navigation).user_can?(:see_tableau_report) %>
              <li class="divider"></li>
              <li class="<%= active_menu2('tableau', 'index') %>">
                <%= link_to 'Tableau Reports', admin_tableau_index_path %>
              </li>
            <% end %>

            <li class="divider"></li>
            <li class="<%= active_menu2('real_time', 'index') %>">
              <%= link_to 'Real Time', admin_real_time_path %>
            </li>
          </ul>
        </li>

        <li class="dropdown <%= active_menu2(['countries', 'lists', 'domains', 'definitions', 'activity_logs']) %>">
          <a href="#" class="dropdown-toggle <%= active_menu2('lookups') %>" data-toggle="dropdown">Other <b class="caret"></b></a>
          <ul class="dropdown-menu">

            <li class="<%= active_menu2('activity_logs') %>">
              <%= link_to 'Activity Log', admin_activity_logs_path %>
            </li>

            <li class="<%= active_menu2('lists', 'menu') %>">
              <% if policy(Navigation).user_can?(:see_lists_link) %>
                <%= link_to 'List Management', menu_admin_lists_path %>
              <% else %>
                <%= link_to 'List Management', '#', style: 'color: darkgrey; cursor: default;' %>
              <% end %>
            </li>

            <li class="<%= active_menu2('dashbid_users') %>">
              <%= link_to 'Dashbid Users', dashbid_list_admin_dashbid_users_path %>
            </li>

            <li class="<%= active_menu2('customer_users') %>">
              <%= link_to 'Customer Users', customer_list_admin_customer_users_path %>
            </li>

            <li class="<%= active_menu2('network_users') %>">
              <%= link_to 'Network Users', network_list_admin_network_users_path %>
            </li>

            <li class="divider"></li>

            <li class="<%= active_menu2('resources') %>">
              <%= link_to 'Help Resources', admin_resources_path %>
            </li>
          </ul>
        </li>

        <% if policy(Navigation).user_can?(:see_admin_dropdown) %>
          <li class="dropdown <%= active_menu2(['users', 'users_roles']) %>">
            <a>Admin-Only <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Groups", admin_groups_path%></li>

              <li><%= link_to "Mobile test version", admin_mobile_index_path, target: '_blank' %></li>

              <li class="<%= active_menu2('countries') %>">
                <%= link_to 'Countries', admin_countries_path %>
              </li>

              <% if policy(Navigation).user_can?(:see_users_roles_link) %>
                <li class="<%= active_menu2('users_roles') %>">
                  <%= link_to 'User Roles', admin_user_roles_path %>
                </li>
              <% end %>

              <% if policy(Navigation).user_can?(:see_hidden_jobs_link) %>
                <li><%= link_to 'Hidden Jobs Menu', admin_jobs_path %></li>
                <li><%= link_to 'Health Checks Menu', admin_health_check_index_path %></li>
                <li class="<%= active_menu2('jobs', 'mysql_processes') %>">
                  <%= link_to "Active MySQL Processes (in new window)" , mysql_processes_admin_jobs_path, target: '_blank' %>
                </li>
                <li><%= link_to "SideKiq (in new window)" , '/admin/sidekiq', target: '_blank' %></li>
              <% end %>

              <li><%= link_to "Vpaids Repository" , admin_vpaids_path %></li>
            </ul>
          </li>
        <% end %>

        <% if policy(Navigation).user_can?(:see_admin_dropdown) %>
          <li><%= link_to 'Env info', 'javascript:;', id: 'toggle-env-info' %></li>
        <% end %>

        <% if current_staff_user %>
          <li>
            <%= link_to 'Revert Impersonation!', impersonate_engine.revert_impersonate_user_path,
                        method: :delete, style: 'color:#f00', class: 'hidden-xs hidden-sm '%>
          </li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to(fa_icon2([:'gear', :lg, :fw]), edit_user_registration_path, title: "Manage #{current_user.email}") %></li>
        <li><%= link_to(fa_icon2([:'sign-out', :lg, :fw]), destroy_user_session_path, method: :delete) %></li>
      </ul>
    </div>
  </div>
</div>